services:
  app:
    build:
      context: ./docker/php
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: laravel_app
    restart: unless-stopped
    working_dir: /var/www/
    volumes:
      - ./src:/var/www
    networks:
      - app_network

  db:
    image: postgres:16-alpine
    platform: linux/amd64
    container_name: postgres_db
    restart: unless-stopped
    environment:
      POSTGRES_DB: ${DB_DATABASE}
      POSTGRES_USER: ${DB_USERNAME}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data
    ports:
      - "5432:5432"
    networks:
      - app_network

  nginx:
    image: nginx:alpine
    platform: linux/amd64
    container_name: nginx_server
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./src:/var/www
      - ./docker/nginx:/etc/nginx/conf.d
      - ./docker/nginx/ssl:/etc/nginx/ssl
    networks:
      - app_network

  node:
    build:
      context: ./docker/node
      dockerfile: Dockerfile
    platform: linux/amd64
    container_name: vue_node
    volumes:
      - ./src:/var/www
    working_dir: /var/www
    networks:
      - app_network

networks:
  app_network:
    driver: bridge

volumes:
  postgres_data: 